# Generated by Django 4.2.7 on 2023-11-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0001_CreateSuperUser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(default='', max_length=255)),
                ('unit_number', models.CharField(blank=True, max_length=4, null=True)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('BC', 'British Columbia'), ('AB', 'Alberta'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Laborador'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=255)),
                ('post_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='Canada', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('mls', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('square_footage', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('title', models.CharField(choices=[('strata', 'Strata'), ('leasehold', 'Leasehold')], max_length=20)),
                ('amenities', models.JSONField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.address')),
            ],
        ),
    ]
