# Generated by Django 4.2.7 on 2023-11-06 08:43

from django.db import migrations
from ..fake_factories import Property as FakeProperty


def create_fake_data(apps, schema_editor):
    Address = apps.get_model("real_estate", "Address")
    Property = apps.get_model("real_estate", "Property")

    properties = {}

    while len(properties) != 150:
        property = FakeProperty()
        properties[property.mls] = property

    for mls in properties:
        property = properties[mls].to_dict()
        address = property.pop("address")

        addr = Address.objects.create(**address)
        Property.objects.create(address=addr, **property)


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_fake_data, migrations.RunPython.noop),
    ]
